data:
  input_file: F:\Projects\MagicDislocation\examples\fcc\s350_16_112\model.data
  type: data
  pos_index:
    - 2
    - 5
  lattice: 3.556
  dxdydz:
    - 0.0
    - 0.204124
    - 0.288675
  data_line_item_num: 8
layerization:
  direction: 2
s_plane:
  center_pos:
    - 0.62809
    - 0.36
    - 1.02566
  type: rect
  edge_range:
    - 20
    - 20
    - 0
move:
  step: 0.408
  direction:
    - 1
    - 0
    - 0
  move_layer_range: 30
