
data:
  input_file: D:\DislocationProject\MagicDislocation\examples\fcc\s350_line_edge\S350.data
  type: data
  pos_index:
    - 2
    - 5
  lattice: 3.556
  dxdydz:
    - 0.5
    - 0.0
    - 0.0
  data_line_item_num: 8
layerization:
  direction: 0
s_plane:
  center_pos:
    - 29.3558
    - -90
    - 0
  type: rect
  edge_range:
    - 0
    - 90.75
    - 200
move:
  step: 0.707
  direction:
    - 0
    - 1
    - 0
  move_layer_range: 40

