data:
  input_file: D:\DislocationProject\MagicDislocation\examples\fcc\cross_loop_001\model.dat
  type: data
  pos_index:
    - 2
    - 5
  lattice: 3.615
  dxdydz:
    - 0.707
    - 0
    - 0
  data_line_item_num: 8
layerization:
  direction: 0
s_plane:
  center_pos:
    - 1.174870856728937
    - 0.204124145
    - 0
  type: loop
  num_points: 48
  fix_coord: 0
  scale: 6
  base: 2
  rotate_para:
    cos_theta: 0.5773502691896258
    cross: True
    margin_flag: 1
    margin_scale: 
      - 1 
      - 12
    margin_base: 6
    target_plane: 
      - -1
      - -1
      - 0
    insert_plane:
      - 1
      - 0
      - 0
move:
  step: 0.408248290463863
  direction:
    - 1
    - 0
    - 0
  move_layer_range: 20

