
data:
  input_file: F:\Projects\MagicDislocation\examples\fcc\s350_line\S350.data
  type: data
  pos_index:
    - 2
    - 5
  lattice: 3.556
  dxdydz:
    - 0.0
    - 0.357
    - 0.0
  data_line_item_num: 8
layerization:
  direction: 1
s_plane:
  center_pos:
    - -71.2
    - 65.7
    - 0
  type: rect
  edge_range:
    - 70.27
    - 0
    - 500
move:
  step: 0.707
  direction:
    - 0
    - 0
    - 1
  move_layer_range: 20

